// This file is auto-generated by generate-bindings
// Do not edit manually. Run `cargo run --bin generate-bindings` to regenerate.
// Or use `npm run generate:types` from the project root.

/**
 * JSON value type for dynamic/untyped data
 */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

/**
 * Settings for temporary project management within a scope
 */
export type TempProjectSettings = { cleanupDays: number; setupGitIdentity: boolean; preferredPackageManager: string }

/**
 * A scope represents a logical grouping of projects (e.g., "Work", "Personal")
 */
export type Scope = { id: string; name: string; color: string | null; icon: string | null; defaultEditorId: string | null; settings: JsonValue | null; sortOrder: number; createdAt: string; updatedAt: string; defaultFolder: string | null; folderScanInterval: number | null; sshAlias: string | null; tempProjectSettings: TempProjectSettings | null }

/**
 * A link associated with a scope (e.g., documentation, CI/CD)
 */
export type ScopeLink = { id: string; scopeId: string; linkType: string; label: string; url: string; sortOrder: number; createdAt: string }

/**
 * A scope with its associated links
 */
export type ScopeWithLinks = { scope: Scope; links: ScopeLink[] }

/**
 * Git configuration for a scope (identity, signing settings)
 */
export type ScopeGitConfig = { scopeId: string; userName: string | null; userEmail: string | null; gpgSign: boolean; gpgSigningMethod: string | null; signingKey: string | null; rawGpgConfig: string | null; configFilePath: string | null; lastCheckedAt: string | null }

/**
 * Record of folder warnings that the user has dismissed
 */
export type IgnoredFolderWarning = { id: string; scopeId: string; projectPath: string; createdAt: string }

/**
 * Git includeIf directive information
 */
export type GitIncludeIf = { condition: string; path: string }

/**
 * A project represents a code repository or folder
 */
export type Project = { id: string; scopeId: string; name: string; path: string; preferredEditorId: string | null; isTemp: boolean; lastOpenedAt: string | null; createdAt: string; updatedAt: string }

/**
 * Cached git status information for a project
 */
export type GitStatusCache = { projectId: string; branch: string | null; ahead: number; behind: number; hasUncommitted: boolean; hasUntracked: boolean; lastCheckedAt: string | null; remoteUrl: string | null }

/**
 * A project with its tags and cached git status
 */
export type ProjectWithStatus = { project: Project; tags: string[]; gitStatus: GitStatusCache | null }

/**
 * An editor that can be used to open projects
 */
export type Editor = { id: string; name: string; command: string; icon: string | null; isAutoDetected: boolean; isAvailable: boolean; createdAt: string }

/**
 * SSH alias configuration
 */
export type SshAlias = { host: string; hostName: string | null; user: string | null; identityFile: string | null }

/**
 * Request to create a new scope
 */
export type CreateScopeRequest = { name: string; color: string | null; icon: string | null; defaultFolder: string | null; sshAlias: string | null }

/**
 * Request to create a new SSH alias
 */
export type CreateSshAliasRequest = { host: string; hostName: string; user: string | null; identityFile: string | null; publicKey: string | null }

/**
 * Request to create a new project
 */
export type CreateProjectRequest = { scopeId: string; name: string; path: string; isTemp: boolean | null }

/**
 * Request to create a new scope link
 */
export type CreateScopeLinkRequest = { scopeId: string; linkType: string; label: string; url: string }

/**
 * Request for creating a temporary project
 * 
 * Matches the request format used by the create_temp_project command
 */
export type TempProjectRequest = { scopeId: string; name: string; packageManager: string; template: string; options: JsonValue | null }

/**
 * Result of creating a temporary project
 */
export type TempProjectResult = { success: boolean; projectId: string | null; projectPath: string | null; error: string | null }

/**
 * Progress event for temporary project creation
 * 
 * Emitted during project creation via temp-project-progress event
 */
export type TempProjectProgress = { line: string; isError: boolean; status: string | null }

/**
 * Options for cloning a repository
 */
export type CloneOptions = { shallow: boolean; branch: string | null; useSshAlias: string | null }

/**
 * Result of cloning a repository
 */
export type CloneResult = { success: boolean; projectId: string | null; projectPath: string | null; error: string | null }

/**
 * Progress event for clone operation
 * 
 * Emitted during clone via clone-progress event
 */
export type CloneProgress = { line: string; isError: boolean; status: string | null }

