// This file is auto-generated by generate-bindings
// Do not edit manually. Run `cargo run --bin generate-bindings` to regenerate.
// Or use `npm run generate:types` from the project root.

/**
 * JSON value type for dynamic/untyped data
 */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

/**
 * Settings for temporary project management within a scope
 */
export type TempProjectSettings = { cleanupDays: number; setupGitIdentity: boolean; preferredPackageManager: string }

/**
 * A scope represents a logical grouping of projects (e.g., "Work", "Personal")
 */
export type Scope = { id: string; name: string; color: string | null; icon: string | null; defaultEditorId: string | null; settings: JsonValue | null; sortOrder: number; createdAt: string; updatedAt: string; defaultFolder: string | null; folderScanInterval: number | null; sshAlias: string | null; tempProjectSettings: TempProjectSettings | null }

/**
 * A link associated with a scope (e.g., documentation, CI/CD)
 */
export type ScopeLink = { id: string; scopeId: string; linkType: string; label: string; url: string; sortOrder: number; createdAt: string }

/**
 * A scope with its associated links
 */
export type ScopeWithLinks = { scope: Scope; links: ScopeLink[] }

/**
 * Git configuration for a scope (identity, signing settings)
 */
export type ScopeGitConfig = { scopeId: string; userName: string | null; userEmail: string | null; gpgSign: boolean; gpgSigningMethod: string | null; signingKey: string | null; rawGpgConfig: string | null; configFilePath: string | null; lastCheckedAt: string | null }

/**
 * Record of folder warnings that the user has dismissed
 */
export type IgnoredFolderWarning = { id: string; scopeId: string; projectPath: string; createdAt: string }

/**
 * Git includeIf directive information
 */
export type GitIncludeIf = { condition: string; path: string }

/**
 * A project represents a code repository or folder
 */
export type Project = { id: string; scopeId: string; name: string; path: string; preferredEditorId: string | null; defaultBranch: string | null; workspaceFile: string | null; isTemp: boolean; isPinned: boolean; groupId: string | null; notes: string | null; description: string | null; lastOpenedAt: string | null; createdAt: string; updatedAt: string }

/**
 * Cached git status information for a project
 */
export type GitStatusCache = { projectId: string; branch: string | null; ahead: number; behind: number; hasUncommitted: boolean; hasUntracked: boolean; lastCheckedAt: string | null; remoteUrl: string | null }

/**
 * A project with its tags and cached git status
 */
export type ProjectWithStatus = { project: Project; tags: string[]; gitStatus: GitStatusCache | null; links: ProjectLink[]; group: ProjectGroup | null; statistics: ProjectStatistics | null }

/**
 * A link associated with a project (e.g., documentation, CI/CD)
 */
export type ProjectLink = { id: string; projectId: string; linkType: string; label: string; url: string; sortOrder: number; createdAt: string }

/**
 * A group for organizing projects within a scope
 */
export type ProjectGroup = { id: string; scopeId: string; name: string; color: string | null; sortOrder: number; createdAt: string }

/**
 * A custom command/script for a project
 */
export type ProjectCommand = { id: string; projectId: string; name: string; command: string; description: string | null; workingDirectory: string | null; sortOrder: number; createdAt: string }

/**
 * Statistics about a project
 */
export type ProjectStatistics = { fileCount: number | null; repoSizeBytes: number | null; commitCount: number | null; lastCommit: LastCommitInfo | null; languages: LanguageInfo[]; contributors: ContributorInfo[] }

/**
 * Information about the last commit
 */
export type LastCommitInfo = { hash: string; message: string; author: string; date: string }

/**
 * Language information
 */
export type LanguageInfo = { name: string; bytes: number; percentage: number }

/**
 * Contributor information
 */
export type ContributorInfo = { name: string; email: string; commitCount: number }

/**
 * An editor that can be used to open projects
 */
export type Editor = { id: string; name: string; command: string; icon: string | null; isAutoDetected: boolean; isAvailable: boolean; supportsWorkspaces: boolean; createdAt: string }

/**
 * SSH alias configuration
 */
export type SshAlias = { host: string; hostName: string | null; user: string | null; identityFile: string | null }

/**
 * Request to create a new scope
 */
export type CreateScopeRequest = { name: string; color: string | null; icon: string | null; defaultFolder: string | null; sshAlias: string | null }

/**
 * Request to create a new SSH alias
 */
export type CreateSshAliasRequest = { host: string; hostName: string; user: string | null; identityFile: string | null; publicKey: string | null }

/**
 * Request to create a new project
 */
export type CreateProjectRequest = { scopeId: string; name: string; path: string; isTemp: boolean | null }

/**
 * Request to create a new scope link
 */
export type CreateScopeLinkRequest = { scopeId: string; linkType: string; label: string; url: string }

/**
 * Request to create a new project link
 */
export type CreateProjectLinkRequest = { projectId: string; linkType: string; label: string; url: string }

/**
 * Request to create a new project group
 */
export type CreateProjectGroupRequest = { scopeId: string; name: string; color: string | null }

/**
 * Request to create a new project command
 */
export type CreateProjectCommandRequest = { projectId: string; name: string; command: string; description: string | null; workingDirectory: string | null }

/**
 * Request for creating a temporary project
 * 
 * Matches the request format used by the create_temp_project command
 */
export type TempProjectRequest = { scopeId: string; name: string; packageManager: string; template: string; options: JsonValue | null }

/**
 * Result of executing a project command
 */
export type CommandResult = { success: boolean; output: string; error: string | null; exitCode: number | null }

/**
 * Result of creating a temporary project
 */
export type TempProjectResult = { success: boolean; projectId: string | null; projectPath: string | null; error: string | null }

/**
 * Progress event for temporary project creation
 * 
 * Emitted during project creation via temp-project-progress event
 */
export type TempProjectProgress = { line: string; isError: boolean; status: string | null }

/**
 * Options for cloning a repository
 */
export type CloneOptions = { shallow: boolean; branch: string | null; useSshAlias: string | null }

/**
 * Result of cloning a repository
 */
export type CloneResult = { success: boolean; projectId: string | null; projectPath: string | null; error: string | null }

/**
 * Progress event for clone operation
 * 
 * Emitted during clone via clone-progress event
 */
export type CloneProgress = { line: string; isError: boolean; status: string | null }

/**
 * Severity level for diagnostic issues.
 */
export type Severity = 
/**
 * Critical issues that prevent functionality (e.g., missing required config)
 */
"error" | 
/**
 * Issues that should be addressed but don't break functionality
 */
"warning" | 
/**
 * Informational notices and suggestions
 */
"info"

/**
 * Rule groups for organizing diagnostic rules.
 */
export type RuleGroup = 
/**
 * Git configuration and identity rules (git/*)
 */
"git" | 
/**
 * Repository health and state rules (repo/*)
 */
"repo" | 
/**
 * Project structure and organization rules (project/*)
 */
"project" | 
/**
 * Security-related rules (security/*)
 */
"security"

/**
 * Metadata about a diagnostic rule.
 */
export type RuleMetadata = { 
/**
 * Unique identifier (e.g., "git/identity-mismatch")
 */
id: string; 
/**
 * Rule group
 */
group: RuleGroup; 
/**
 * Human-readable name (e.g., "Identity Mismatch")
 */
name: string; 
/**
 * Description of what this rule checks
 */
description: string; 
/**
 * Whether this rule is enabled by default
 */
defaultEnabled: boolean; 
/**
 * Default severity level
 */
defaultSeverity: Severity; 
/**
 * Max feature this rule depends on (None = always active)
 */
requiredFeature: string | null; 
/**
 * Whether this rule applies at scope level (vs project level)
 */
isScopeLevel: boolean }

/**
 * A diagnostic issue found during scanning.
 */
export type DiagnosticIssue = { 
/**
 * Unique identifier for this issue instance
 */
id: string; 
/**
 * Scope this issue belongs to
 */
scopeId: string; 
/**
 * Project this issue relates to (None for scope-level issues)
 */
projectId: string | null; 
/**
 * Rule that generated this issue (e.g., "git/identity-mismatch")
 */
ruleId: string; 
/**
 * Severity level
 */
severity: Severity; 
/**
 * Short title describing the issue
 */
title: string; 
/**
 * Detailed description
 */
description: string; 
/**
 * Expected value (for mismatch issues)
 */
expectedValue: string | null; 
/**
 * Actual value found (for mismatch issues)
 */
actualValue: string | null; 
/**
 * Additional metadata as JSON
 */
metadata: JsonValue | null; 
/**
 * Whether this issue has been dismissed by the user
 */
dismissed: boolean; 
/**
 * When this issue was first detected
 */
createdAt: string; 
/**
 * When this issue was last updated
 */
updatedAt: string }

/**
 * Request to fix a diagnostic issue.
 */
export type DiagnosticFix = { issueId: string; ruleId: string; 
/**
 * Type of fix to apply (rule-specific)
 */
fixType: string; 
/**
 * Additional parameters for the fix
 */
params: JsonValue | null }

/**
 * A disabled diagnostic rule.
 */
export type DisabledRule = { id: string; 
/**
 * Scope this rule is disabled for (None = global)
 */
scopeId: string | null; ruleId: string; createdAt: string }

/**
 * Scan state for a scope.
 */
export type ScanState = { scopeId: string; lastScanAt: string | null; scanDurationMs: number | null; issuesFound: number }

/**
 * Summary of diagnostics for a scope.
 */
export type ScopeDiagnosticsSummary = { scopeId: string; errorCount: number; warningCount: number; infoCount: number; totalCount: number; lastScanAt: string | null }

